# Autograd: 自动微分

PyTorch 中所有神经网络的核心是 autograd 包。autograd 包为张量上的所有操作提供了自动微分，它是一个在运行时被定义的框架，每次迭代都可能不同。

## 张量

In [1]:
import torch

创建张量并跟踪计算：

In [2]:
x = torch.ones(2, 2, requires_grad = True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


执行张量计算：

In [3]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward>)


In [4]:
print(y.grad_fn)

对 y 执行更多计算：

In [5]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward>) tensor(27., grad_fn=<MeanBackward1>)


.requires_grad_ 会改变张量的 requires_grad 状态，如果未指定默认为 false

In [6]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


## 梯度

反向传播。out 只包含一个标量，out.backward() 等价于 out.backward(torch.tensor(1)).

In [7]:
out.backward()

输出 d(out)/dx：

In [8]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


更疯狂的自动微分：

In [9]:
x = torch.randn(3, requires_grad = True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2

print(y)

tensor([-742.9510, -604.8928,  375.6190], grad_fn=<MulBackward>)


In [10]:
gradients = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(gradients)

print(x.grad)

tensor([ 51.2000, 512.0000,   0.0512])


停止跟踪张量的计算历史：

In [11]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

print((x ** 2).requires_grad)

True
True
False
True
