# 什么是 PyTorch？

## 起步

### 张量

In [2]:
from __future__ import print_function
import torch

构建未初始化矩阵：

In [6]:
x = torch.empty(5, 3)
print(x)

tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000]])


构建随机初始化矩阵：

In [5]:
x = torch.rand(5, 3)
print(x)

tensor([[0.4153, 0.9497, 0.2963],
        [0.6906, 0.6767, 0.4146],
        [0.3722, 0.6882, 0.2901],
        [0.7573, 0.0626, 0.6847],
        [0.2255, 0.3006, 0.6990]])


构建零矩阵并指定数据类型：

In [8]:
x = torch.zeros(5, 3 ,dtype = torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


由数据直接构造张量：

In [10]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


根据现有张量构建张量，重用输入张量的属性，除非被重写：

In [13]:
x = x.new_ones(5, 3, dtype = torch.double)
print(x)

x = torch.randn_like(x, dtype = torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.4113,  1.3747,  0.3750],
        [-1.3947,  0.6144, -0.9689],
        [-0.6577,  0.7567,  0.7351],
        [ 0.1371,  0.8914, -1.0119],
        [-0.7754, -0.4901, -1.1299]])


获得大小：

In [14]:
print(x.size())

torch.Size([5, 3])


### 操作

加法：语法1

In [16]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 1.6462,  1.8169,  1.0666],
        [-1.1098,  0.8244, -0.2489],
        [ 0.1591,  1.2404,  0.7913],
        [ 0.2293,  1.5133, -0.0208],
        [-0.1980,  0.0280, -0.4938]])


加法：语法2

In [19]:
print(torch.add(x, y))

tensor([[ 1.6462,  1.8169,  1.0666],
        [-1.1098,  0.8244, -0.2489],
        [ 0.1591,  1.2404,  0.7913],
        [ 0.2293,  1.5133, -0.0208],
        [-0.1980,  0.0280, -0.4938]])


加法：输出张量作为参数

In [21]:
result = torch.empty(5, 3)
torch.add(x, y, out = result)
print(result)

tensor([[ 1.6462,  1.8169,  1.0666],
        [-1.1098,  0.8244, -0.2489],
        [ 0.1591,  1.2404,  0.7913],
        [ 0.2293,  1.5133, -0.0208],
        [-0.1980,  0.0280, -0.4938]])


就地相加：

In [22]:
y.add_(x) # adds x to y
print(x)

tensor([[ 1.4113,  1.3747,  0.3750],
        [-1.3947,  0.6144, -0.9689],
        [-0.6577,  0.7567,  0.7351],
        [ 0.1371,  0.8914, -1.0119],
        [-0.7754, -0.4901, -1.1299]])


使用 Numpy 风格的索引：

In [24]:
print(x)
print(x[:, 1])

tensor([[ 1.4113,  1.3747,  0.3750],
        [-1.3947,  0.6144, -0.9689],
        [-0.6577,  0.7567,  0.7351],
        [ 0.1371,  0.8914, -1.0119],
        [-0.7754, -0.4901, -1.1299]])
tensor([ 1.3747,  0.6144,  0.7567,  0.8914, -0.4901])


改变大小：

In [25]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8) # -1 表示从其他维度推断
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


单元素张量获取其值：

In [27]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([1.2959])
1.2958693504333496


# 与 Numpy

Torch 张量与 Numpy 数组共享内存位置，改变一个会同时改变另一个。

## Torch 张量转换为 Numpy 数组

In [28]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [29]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


观察 numpy 数组的值如何发生变化：

In [30]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### Numpy 数组转换为 Torch 张量

In [31]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out = a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


所有 CPU 中的张量除了 CharTensor 支持转换为 Numpy 格式并转换回来。

## CUDA 张量

使用 .to 方法将张量移动到任意设备 

In [33]:
if(torch.cuda.is_available()):
    device = torch.device("cuda")               # CUDA 设备对象
    y = torch.ones_like(x, device = device) # GPU 上创建张量
    x = x.to(device)
    z = x + y
    print(x)
    print(z.to("cpu",torch.double))             # .to 方法能一并改变数据类型